title = "Test Environments"
github_token = "a-personal-access-token"
github_owner = "tweedegolf"
github_repo = "etes"
max_services = 10
server_port = 3000
proxy_port = 3001
github_client_id = "some-oauth-client-id"
github_client_secret = "some-oauth-secret"
authorize_url = "https://example.com/etes/authorize"
admins = ["example"]
api_key = "more-secret-than-this"
session_key = "more-entropy-than-this"
command_args = ["{port}"]
command_env = {"FOO" = "bar", "BAR" = "foo"}
favicon = "ðŸ™‚"
words = ['foo', 'bar', 'baz']
